# County Business Pattern 2010

In [1]:
import pandas as pd
import numpy as np

cbp = pd.read_csv("../../external_data/cbp/cbp10co.csv")

In [88]:
col = ['fipstate', 'fipscty', 'naics', 'est']
cbp_col = cbp[col]
cbp_col = cbp_col[cbp_col['naics']=='722410']
cbp_col.columns = ['STATEFP','COUNTYFP', 'naics','est']
cbp_col.head()

      STATEFP  COUNTYFP   naics  est
662         1         1  722410    1
1910        1         3  722410   10
2530        1         5  722410    1
4424        1        13  722410    1
5489        1        15  722410    5

## Combine the population data

In [108]:
popu = pd.read_csv("../../external_data/cbp/CenPop2010_Mean_CO.txt")
popu = popu[popu['STATEFP']!=72]
# popu
df = popu.merge(cbp_col, on=['STATEFP','COUNTYFP'], how='outer')
df = df[~df['COUNAME'].isnull()]
df['est'] = df['est'].fillna(0)
df['naics'] = df['naics'].fillna(0)
df

,STATEFP,COUNTYFP,COUNAME,STNAME,POPULATION,LATITUDE,LONGITUDE,naics,est
0,1,1,Autauga,Alabama,54571,32.500389,-86.494165,722410,1
1,1,3,Baldwin,Alabama,182265,30.548923,-87.762381,722410,10
2,1,5,Barbour,Alabama,27457,31.844036,-85.310038,722410,1
3,1,7,Bibb,Alabama,22915,33.030921,-87.127659,NaN,0
4,1,9,Blount,Alabama,57322,33.955243,-86.591491,NaN,0
5,1,11,Bullock,Alabama,10914,32.116327,-85.701192,NaN,0
6,1,13,Butler,Alabama,20947,31.773539,-86.653550,722410,1
7,1,15,Calhoun,Alabama,118572,33.725460,-85.819442,722410,5
8,1,17,Chambers,Alabama,34215,32.860439,-85.266474,NaN,0
9,1,19,Cherokee,Alabama,25989,34.179333,-85.629194,NaN,0
10,1,21,Chilton,Alabama,43643,32.877547,-86.687406,722410,1
11,1,23,Choctaw,Alabama,13859,32.016562,-88.264164,722410,1
12,1,25,Clarke,Alabama,25833,31.685685,-87.815673,NaN,0
13,1,27,Clay,Alabama,13932,33.272412,-85.820227,NaN,0
14,1,29,Cleburne,Alabama,14972,33.629770,-85.494315,NaN,0
15,1,31,Coffee,Alabama,49948,31.354433,-85.904715,722410,2
16,1,33,Colbert,Alabama,54428,34.723385,-87.685151,722410,5
17,1,35,Conecuh,Alabama,13228,31.418674,-86.996483,NaN,0
18,1,37,Coosa,Alabama,11539,32.975932,-86.155035,722410,1
19,1,39,Covington,Alabama,37765,31.282449,-86.410955,722410,3
20,1,41,Crenshaw,Alabama,13906,31.743487,-86.297080,NaN,0
21,1,43,Cullman,Alabama,80406,34.162362,-86.831859,NaN,0
22,1,45,Dale,Alabama,50251,31.383346,-85.641269,722410,6
23,1,47,Dallas,Alabama,43820,32.408815,-87.034955,722410,2
24,1,49,DeKalb,Alabama,71109,34.455110,-85.817208,NaN,0
25,1,51,Elmore,Alabama,79303,32.559652,-86.225647,722410,4
26,1,53,Escambia,Alabama,38319,31.088737,-87.282053,722410,2
27,1,55,Etowah,Alabama,104430,34.013693,-86.025393,722410,7
28,1,57,Fayette,Alabama,17241,33.726422,-87.770355,NaN,0
29,1,59,Franklin,Alabama,31704,34.460481,-87.793594,NaN,0
...,...,...,...,...,...,...,...,...,...
3113,55,129,Washburn,Wisconsin,15911,45.847241,-91.834412,722410,20
3114,55,131,Washington,Wisconsin,131887,43.347344,-88.215167,722410,49
3115,55,133,Waukesha,Wisconsin,389891,43.034419,-88.236902,722410,100
3116,55,135,Waupaca,Wisconsin,52410,44.432371,-88.937106,722410,37
3117,55,137,Waushara,Wisconsin,24496,44.101150,-89.225960,722410,22
3118,55,139,Winnebago,Wisconsin,166994,44.100643,-88.540068,722410,109
3119,55,141,Wood,Wisconsin,74749,44.478782,-89.963901,722410,56
3120,56,1,Albany,Wyoming,36299,41.314993,-105.598281,722410,9
3121,56,3,Big Horn,Wyoming,11668,44.629497,-108.244578,722410,3
3122,56,5,Campbell,Wyoming,46133,44.254397,-105.494894,722410,12
3123,56,7,Carbon,Wyoming,15885,41.670117,-107.083924,722410,15
3124,56,9,Converse,Wyoming,13833,42.794110,-105.527589,722410,5
3125,56,11,Crook,Wyoming,7083,44.432535,-104.625297,722410,4
3126,56,13,Fremont,Wyoming,40123,43.013591,-108.608913,722410,17
3127,56,15,Goshen,Wyoming,13249,42.046971,-104.220514,722410,6
3128,56,17,Hot Springs,Wyoming,4812,43.661835,-108.230408,722410,2
3129,56,19,Johnson,Wyoming,8569,44.290845,-106.693517,722410,2
3130,56,21,Laramie,Wyoming,91738,41.153225,-104.773209,722410,15
3131,56,23,Lincoln,Wyoming,18106,42.580437,-110.841375,722410,6
3132,56,25,Natrona,Wyoming,75450,42.844218,-106.336877,722410,17
3133,56,27,Niobrara,Wyoming,2484,42.809987,-104.465879,NaN,0
3134,56,29,Park,Wyoming,28205,44.615174,-108.973460,722410,4
3135,56,31,Platte,Wyoming,8667,42.102310,-104.928453,722410,3
3136,56,33,Sheridan,Wyoming,29116,44.781091,-106.974338,722410,9
3137,56,35,Sublette,Wyoming,10247,42.780901,-109.961153,722410,5
3138,56,37,Sweetwater,Wyoming,43806,41.580266,-109.295115,722410,20
3139,56,39,Teton,Wyoming,21294,43.494174,-110.784353,722410,3
3140,56,41,Uinta,Wyoming,21118,41.271860,-110.767519,722410,2
3141,56,43,Washakie,Wyoming,8533,44.012142,-107.911552,722410,3
3142,56,45,Weston,Wyoming,7208,43.910214,-104.312414,722410,3